### ISSUE TITLE
Can't connect to MS SQL Server 2019 by Docker

### ISSUE THREAD

**Issue by NilkOne** [k1LoW/tbls#334] opened 2022-02-15 14:57 UTC
### What happened
Hello,

I try to use TLBS but I get errors,
How to params the query connection ?

User: bob
Password: secret
Server #1 Host: SRV-DEV-TEST
Server #2 Host: localhost
Server#2 with instance name : SQL_ABC_19

Connection to Server #1 : 

```
docker run ghcr.io/k1low/tbls doc sqlserver://bob:secret@SRV-DEV-TEST:1433

invalid DSN: parse sqlserver://bob:secret@SRV-DEV-TEST:1433 -> &dburl.URL{URL:url.URL{Scheme:"sqlserver", Opaque:"", User:(*url.Userinfo)(0xc0004bc180), Host:"SRV-DEV-TEST:1433", Path:"", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}, OriginalScheme:"sqlserver", Transport:"tcp", Driver:"sqlserver", Unaliased:"sqlserver", DSN:"Password=secret;Port=1433;Server=SRV-DEV-TEST;User ID=bob", hostPortDB:[]string{"SRV-DEV-TEST", "1433", ""}}
```

Connection to Server #2 : 

```
docker run ghcr.io/k1low/tbls doc sqlserver://bob:secret@localhost:1433/SQL_ABC_19

C:\Users\kevin>docker run ghcr.io/k1low/tbls doc sqlserver://bob:secret@localhost:1433/SQL_ABC_19
unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connect: connection refused
```

I precise that I can connect to servers by using SQL Service Management Studio

### Environment

- `tbls version` [v1.54.2](https://github.com/users/k1low/packages/container/tbls/11925981?tag=v1.54.2)
- Database version : Microsoft SQL Server 2019 - 15.0.2080.9 (X64) 
- OS : Windows 10
- Shell : bash

**Comment by k1LoW** [comment] 2022-02-16 02:39
This is a duplicate of https://github.com/k1LoW/tbls/issues/237#issuecomment-1040308034, so I'll close it.

**Closed by k1LoW** 2022-02-16 02:39 UTC
Labels: bug
